// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_IgBbhbED66s17hAdbXKbGNrodhoi_k',
    appId: '1:81130982036:web:cf1c3b7ffa817aeae08281',
    messagingSenderId: '81130982036',
    projectId: 'earnedon-6ce38',
    authDomain: 'earnedon-6ce38.firebaseapp.com',
    storageBucket: 'earnedon-6ce38.appspot.com',
    measurementId: 'G-XKW8MKP125',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNw4u4t15ZjqV6OhZnq9RT1SuptsQmLA',
    appId: '1:81130982036:android:b69e1e154145fd8de08281',
    messagingSenderId: '81130982036',
    projectId: 'earnedon-6ce38',
    storageBucket: 'earnedon-6ce38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWZeNO0h411lokVuwoBJI4x7qehswOU0',
    appId: '1:81130982036:ios:cb0a1f6430c3d6dee08281',
    messagingSenderId: '81130982036',
    projectId: 'earnedon-6ce38',
    storageBucket: 'earnedon-6ce38.appspot.com',
    androidClientId: '81130982036-q1pcla86vc04kcbu1dlajf4skjjlsqt9.apps.googleusercontent.com',
    iosClientId: '81130982036-9knclvli2c1hgkqgjfj64a8032131bop.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedBudgetBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkWZeNO0h411lokVuwoBJI4x7qehswOU0',
    appId: '1:81130982036:ios:3965fed1759bf080e08281',
    messagingSenderId: '81130982036',
    projectId: 'earnedon-6ce38',
    storageBucket: 'earnedon-6ce38.appspot.com',
    androidClientId: '81130982036-q1pcla86vc04kcbu1dlajf4skjjlsqt9.apps.googleusercontent.com',
    iosClientId: '81130982036-kpqs838l88lrdea2sni0seo8802kngbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedBudgetBook.RunnerTests',
  );
}
